import enum


class SystemState(str, enum.Enum):
    NORMAL = "NORMAL"
    WATCH = "WATCH"
    NADIR_COMPLETE = "NADIR_COMPLETE"
    ZENITH = "ZENITH"
    CONSTRAINT_DISSOLVING = "CONSTRAINT_DISSOLVING"


class SignalType(str, enum.Enum):
    SHORT_INTEREST = "SHORT_INTEREST"
    ANALYST_SENTIMENT = "ANALYST_SENTIMENT"
    INSIDER_BUYING = "INSIDER_BUYING"
    JOB_POSTING_VELOCITY = "JOB_POSTING_VELOCITY"
    SQUEEZE_PROBABILITY = "SQUEEZE_PROBABILITY"
    # GRR is post-entry monitoring only, not a detection signal
    GRR_MONITORING = "GRR_MONITORING"


class EvidenceDirection(str, enum.Enum):
    STRONGLY_BULLISH = "STRONGLY_BULLISH"
    BULLISH = "BULLISH"
    NEUTRAL = "NEUTRAL"
    BEARISH = "BEARISH"
    STRONGLY_BEARISH = "STRONGLY_BEARISH"


class EvidenceConfidence(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class OutcomeDirection(str, enum.Enum):
    CONFIRMED = "CONFIRMED"
    DENIED = "DENIED"
    AMBIGUOUS = "AMBIGUOUS"


class PositionStatus(str, enum.Enum):
    OPEN = "OPEN"
    CLOSED_PROFIT = "CLOSED_PROFIT"
    CLOSED_LOSS = "CLOSED_LOSS"
    CLOSED_TIMEOUT = "CLOSED_TIMEOUT"
    CLOSED_FALSIFIED = "CLOSED_FALSIFIED"


class AlertType(str, enum.Enum):
    SIGNAL_SPIKE = "SIGNAL_SPIKE"
    WATCH_TRIGGERED = "WATCH_TRIGGERED"
    NADIR_COMPLETE = "NADIR_COMPLETE"
    FALSIFICATION_DETECTED = "FALSIFICATION_DETECTED"
    REHABILITATION_SIGNAL = "REHABILITATION_SIGNAL"
    PREDICTION_RESOLVING = "PREDICTION_RESOLVING"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    TIME_LIMIT_REACHED = "TIME_LIMIT_REACHED"
    STOP_LOSS_TRIGGERED = "STOP_LOSS_TRIGGERED"
    INSIDER_BUYING_STOPPED = "INSIDER_BUYING_STOPPED"
    CONVICTION_SHIFT = "CONVICTION_SHIFT"


class AlertPriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# The 5 detection signals (must all be met for NADIR_COMPLETE)
DETECTION_SIGNALS = frozenset({
    SignalType.SHORT_INTEREST,
    SignalType.ANALYST_SENTIMENT,
    SignalType.INSIDER_BUYING,
    SignalType.JOB_POSTING_VELOCITY,
    SignalType.SQUEEZE_PROBABILITY,
})
