import enum


class SystemState(str, enum.Enum):
    NORMAL = "NORMAL"
    WATCH = "WATCH"
    NADIR_COMPLETE = "NADIR_COMPLETE"
    ZENITH = "ZENITH"
    CONSTRAINT_DISSOLVING = "CONSTRAINT_DISSOLVING"


class SignalType(str, enum.Enum):
    SHORT_INTEREST = "SHORT_INTEREST"
    ANALYST_SENTIMENT = "ANALYST_SENTIMENT"
    INSIDER_BUYING = "INSIDER_BUYING"
    GRR_STABILITY = "GRR_STABILITY"
    MORAL_LANGUAGE = "MORAL_LANGUAGE"


class BeliefLayer(str, enum.Enum):
    SURFACE = "SURFACE"
    FINANCIAL = "FINANCIAL"
    STRUCTURAL = "STRUCTURAL"
    AXIOM = "AXIOM"


class NetDirection(str, enum.Enum):
    STRONGLY_CONFIRMING = "STRONGLY_CONFIRMING"
    CONFIRMING = "CONFIRMING"
    NEUTRAL = "NEUTRAL"
    CONTRADICTING = "CONTRADICTING"
    STRONGLY_CONTRADICTING = "STRONGLY_CONTRADICTING"


class OutcomeDirection(str, enum.Enum):
    CONFIRMED = "CONFIRMED"
    DENIED = "DENIED"
    AMBIGUOUS = "AMBIGUOUS"


class PositionStatus(str, enum.Enum):
    OPEN = "OPEN"
    CLOSED_PROFIT = "CLOSED_PROFIT"
    CLOSED_LOSS = "CLOSED_LOSS"
    CLOSED_TIMEOUT = "CLOSED_TIMEOUT"
    CLOSED_FALSIFIED = "CLOSED_FALSIFIED"


class AlertType(str, enum.Enum):
    SIGNAL_SPIKE = "SIGNAL_SPIKE"
    WATCH_TRIGGERED = "WATCH_TRIGGERED"
    NADIR_COMPLETE = "NADIR_COMPLETE"
    FALSIFICATION_DETECTED = "FALSIFICATION_DETECTED"
    REHABILITATION_SIGNAL = "REHABILITATION_SIGNAL"
    PREDICTION_RESOLVING = "PREDICTION_RESOLVING"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    TIME_LIMIT_REACHED = "TIME_LIMIT_REACHED"
    STOP_LOSS_TRIGGERED = "STOP_LOSS_TRIGGERED"
    INSIDER_BUYING_STOPPED = "INSIDER_BUYING_STOPPED"


class AlertPriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
